### ISSUE TITLE
Tmux Ctrl-b change to Ctrl-a

### ISSUE THREAD

**Issue by ttbakiatwoam** [squarefrog/dotfiles#40]
Thanks for the Keyboard/Mouse configs. 

Just FYI on most BASH installs ctrl-a is already assigned. 

Ctrl + a   Go to the beginning of the line (Home)

http://ss64.com/bash/syntax-keyboard.html

**Comment by squarefrog** [comment]
Thanks - but I use ZSH with Vim keybindings so if the emacs home command doesn't work it doesn't matter to me!
